### ISSUE TITLE
Issue with Dataset Download

### ISSUE THREAD

**Issue by mrachelyu** [Morpheus3000/ShadingNet#1]
Hello, I am very interested in your project and wanted to try downloading the dataset. However, when I attempt to download ShadingNet_Dataset_Release.z05, the following error appears:

{ "message": "Storage exception: Unexpected scenario inst_id=201 state=ic_failure", "code": "StorageException" }

I have tried downloading with both Chrome and Edge browsers, but I encounter the same issue. Could you please advise me on how to resolve this problem?

**Comment by Morpheus3000** [comment]
Hi!

Thanks for you interest! Regarding the issue, strange that it's that one download that doesn't work. It might be that the link is corrupted and pointing to an invalid download. I will have to contact with the people managing our data storage servers.

But in the meantime, I have reuploaded that part again, so if you now go to the link, you should see another ShadingNet_Dataset_Release.z05 at the end of the list. That should download without any issues. I just checked it myself.

Thanks for bringing the issue to attention. Hopefully everything else works out!

Cheers.

**Comment by mrachelyu** [comment]
Hello, 
I saw the new file and have successfully downloaded it. 
Thank you very much for your help! 
Wishing you a wonderful day!

**Comment by Morpheus3000** [comment]
Glad to hear that worked! I'll close the issue. But feel free to reach out if you need help.
